apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-core
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts: [app.4.230.152.143.nip.io]
      secretName: app-tls
  rules:
    - host: app.4.230.152.143.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backspringboot
                port:
                  number: 8080
          - path: /public
            pathType: Prefix
            backend:
              service:
                name: backspringboot
                port:
                  number: 8080
